require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

# Disables "Too many expectations."
RSpec/MultipleExpectations:
  Enabled: false

# Disables "Example has too many lines [#X/5]"
RSpec/ExampleLength:
  Enabled: false